# lowercase
name = 'ada lovelace'
print(name)
print(type(name))
print(len(name))
print(name.lower())
print(name.upper())
print(name.capitalize())
print(name.format())
print(name.casefold())
print(name.count(name))
print(name.find('c'))
print(name.format('a'))
print(name.__add__('mike'))
print(name.__class__('adalovelace'))
print(name.__contains__('ada'))
# print(name.__delattr__('mike'))
# print(name.__dir__('adalovelace'))
# print(name.__doc__('adalovelace'))
print(name.__eq__('adalovelace'))
print(name.format('adalovelace'))
print(name.__ge__('adalovelace'))
# print(name.__getattribute__('adalovelace'))
# print(name.__getitem__('adalovelace'))
# print(name.__getitem__('adalovelace'))
# print(name.__getnewargs__('adalovelace'))
# print(name.__gt__('adalovelace'))
# print(name.__hash__('adalovelace'))
# print(name.__init__('adalovelace'))
# print(name.__init_subclass('adalovelace'))
# print(name.__init_subclass('adalovelace'))
print(name.__iter__('adalovelace'))
print(name.__length__('adalovelace'))



